[package]
name = "spoof"
version = "0.1.0"
edition = "2021"

[dependencies]
etherparse = "0.15.0"
futures = "0.3.30"
libc = "0.2.158"
pcap = { version = "2.1.0", features = ["capture-stream"] }
tokio = { version = "1.40.0", features = ["full"] }
